export const errorMessages = {
  InvalidLocation: 'Invalid location',
  InvalidInput: 'Invalid input',
  LocationRequired: 'Location is required and must not be empty.',
  LocationNotFound: 'Location not found',
  WeatherServiceUnavailableError: 'Weather service unavailable.',
  WeatherServiceUnavailableMessage: 'Weather service is currently unavailable. Please try again later.',
  FailedToFetchWeatherData: 'Failed to fetch weather data',
  InternalServerError: 'Internal server error',
  InternalServerMessage: 'An unexpected error occurred while processing your request.',
  FailedToClearCacheError: 'Failed to clear cache',
  FailedToClearCacheMessage: 'An error occurred while clearing the weather cache.',
  CacheStatisticsError: 'Failed to get cache statistics',
  CacheStatisticsMessage: 'An error occurred while retrieving cache statistics.',
  FailedToFetchWidgetsError: 'Failed to fetch widgets',
  FailedToFetchWidgetsMessage: 'An error occurred while retrieving widgets from the database.',
  WidgetAlreadyExistsError: 'Widget already exists',
  WidgetAlreadyExistsMessage: (location: string) => `A widget for "${location}" already exists.`,
  FailedToCreateWidgetError: 'Failed to create widget',
  FailedToCreateWidgetMessage: 'An error occurred while creating the widget.',
  InvalidWidgetIDError: 'Invalid ID format',
  InvaildWidgetIDMessage: 'The provided widget ID is not valid.',
  WidgetNotFoundError: 'Widget not found',
  WidgetNotFoundMessage: (id: string) => `Widget with ID ${id} does not exist.`,
  FailedToDeleteWidgetError: 'Failed to delete widget',
  FailedToDeleteWidgetMessage: 'An error occurred while deleting the widget.',
  FailedToFetchWidgetError: 'Failed to fetch widget',
  FailedToFetchWidgetMessage: 'An error occurred while retrieving the widget.',
  ServiceTimeoutError: (serviceName: string) => `${serviceName} service timeout - please try again`,
  RateLimitExceededMessage: 'Too many requests from this IP, please try again later.',
  RouteNotFound: 'Route not found',
  RouteNotFoundMessage: (route: string) => `The requested route ${route} does not exist.`,
}

export const successMessages = {
  CacheCleared: 'Weather cache cleared successfully',
  WidgetDeleted: 'Widget deleted successfully',
};